---
aws_region: us-east-2
aws_subnet_az: us-east-2b

network_interface: eth0

metrics_ec2_image_id: ami-916f59f4
metrics_ec2_instance_type: c4.large
metrics_spot_price: 0.05
metrics_spot_type: one-time

zookeeper_ec2_image_id: ami-916f59f4
zookeeper_ec2_instance_type: c4.large
zookeeper_spot_price: 0.05
zookeeper_spot_type: one-time

onyx_peer_ec2_image_id: ami-916f59f4
onyx_peer_ec2_instance_type: c4.large #c4.xlarge
onyx_peer_spot_price: 0.07
onyx_peer_spot_type: one-time

n_zookeeper_machines: 1
n_onyx_peer_machines: 2

riemann_port: 5555
lein_version: 2.5.2

onyx_core_version: 3e1dcb3ebbc502ff05e771c0f096e0b0b91659d3
onyx_benchmark_version: 2eada11acd6b50a7e0fbbba1c28bd0de40666f09

onyx_n_virtual_peers: 6
onyx_log_level: info
onyx_deployment_id: onyx-benchmark-1
onyx_batch_size: 20
onyx_max_pending: 100000
onyx_peer_join_backoff: 500
onyx_peer_port: 40000
onyx_job_scheduler: ":onyx.job-scheduler/greedy"
onyx_task_scheduler: ":onyx.task-scheduler/colocated"

onyx_aeron_media_driver_mode: shared
onyx_aeron_embedded_driver: false
onyx_aeron_short_circuit: true
onyx_aeron_n_subscribers: 2
onyx_aeron_write_buffer_size: 200000
onyx_aeron_offer_idle_strategy: ":high-restart-latency"
onyx_aeron_poll_idle_strategy: ":high-restart-latency"

onyx_acker_percentage: 25
onyx_acker_exempt_inputs: false

media_driver_java_opts: "-server"

peer_java_opts: >
  -server
  -XX:+UnlockCommercialFeatures
  -XX:+FlightRecorder
  -XX:+UnlockDiagnosticVMOptions
  -XX:StartFlightRecording=duration=1080s,filename=peer_recording.jfr
