---
- name: Launch the Onyx Peers instances
  register: onyx_peers_ec2
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    assign_public_ip: yes
    group: "[{{ onyx_cluster_id }}] Onyx Public Subnet Security Group"
    zone: "{{ aws_subnet_az }}"
    region: "{{ aws_region }}"
    key_name: "{{ aws_key_name }}"
    image: "{{ onyx_peer_ec2_image_id }}"
    instance_type: "{{ onyx_peer_ec2_instance_type }}"
    instance_tags:
      Name: "[{{ onyx_cluster_id }}] peer"
      Role: onyx-peer
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    spot_price: "{{ onyx_peer_spot_price }}"
    spot_type: "{{ onyx_peer_spot_type }}"
    exact_count: "{{ n_onyx_peer_machines }}"
    count_tag:
      Name: "[{{ onyx_cluster_id }}] peer"
      Role: onyx-peer
    wait: yes
    wait_timeout: 300

- name: Wait for SSH on new Peer machines
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 15
    timeout: 320
    state: started
  with_items: "{{ onyx_peers_ec2.instances | rejectattr('state', 'equalto', 'terminated') | list }}"

- name: Add public Onyx Peers host to inventory
  add_host:
    name: "{{ item.public_dns_name }}"
    groups: peer
  with_items: "{{ onyx_peers_ec2.instances | rejectattr('state', 'equalto', 'terminated') | list }}"
