# Good article: http://jeremievallee.com/2016/07/27/aws-vpc-ansible/

- name: Create the VPC
  ec2_vpc_net:
    name:             "[{{ onyx_cluster_id }}] Onyx VPC"
    state:            present
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    cidr_block:       "{{ vpc_cidr_block }}"
    region:           "{{ aws_region }}"
    #dns_hostnames:    yes #TODO:
    #dns_support:      yes #TODO:
    tenancy:          default #TODO: Try dedicated
    tags:
      Name:           "[{{ onyx_cluster_id }}] Onyx VPC"
      Environment:    "Onyx"
      ClusterId:      "{{ onyx_cluster_id }}"
  register: onyx_vpc

- name: Set VPC ID in variable
  set_fact:
    vpc_id:           "{{ onyx_vpc.vpc.id }}"


- name: Create public VPC subnet
  ec2_vpc_subnet:
    vpc_id:         "{{ vpc_id }}"
    state: present
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    cidr:           "{{ public_subnet_1_cidr }}"
    az:             "{{ aws_subnet_az }}"
    region:         "{{ aws_region }}"
    tags:
      Name:         "[{{ onyx_cluster_id }}] Onyx Subnet"
      Environment:  "Onyx"
  register: onyx_vpc_subnet

- name: Bind VPC subnet ID
  set_fact:
    vpc_subnet_id:  "{{ onyx_vpc_subnet.subnet.id }}"


- name: Create Internet Gateway for VPC
  ec2_vpc_igw:
    vpc_id:         "{{ vpc_id }}"
    state:          present
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region:         "{{ aws_region }}"
  register: onyx_vpc_igw

- name: Bind Internet Gateway ID in variable
  set_fact:
    igw_id:         "{{ onyx_vpc_igw.gateway_id }}"


- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    tags:
      Name:           "Public"
    subnets:
      - "{{ vpc_subnet_id }}"
    routes:
      - dest:         "0.0.0.0/0"
        gateway_id:   "{{ igw_id }}"



- name: Create the public subnet security group
  ec2_group:
    name: "[{{ onyx_cluster_id }}] Onyx Public Subnet Security Group"
    description: "Base Security group for Onyx"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    purge_rules: yes
    purge_rules_egress: yes
    rules:
      - proto: icmp
        from_port: -1
        to_port: -1
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 1
        to_port: 65535
        cidr_ip: "0.0.0.0/0"
      - proto: udp
        from_port: 1
        to_port: 65535
        cidr_ip: "0.0.0.0/0"

#- name:               Create Main Security Group
#  ec2_group:
#    rules:
#      - proto:        "tcp"
#        from_port:    "22"
#        to_port:      "22"
#        cidr_ip:      "{{ my_ip }}/32"