---
- name: Install Riemann config
  template:
    src: riemann.config
    dest: /srv/riemann.config
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Run Riemann container
  docker_container:
    name: riemann
    image: rlister/riemann:latest
    network_mode: host
    detach: yes
    state: started
    restart_policy: always
    #restart_retries: 128 #conflicts with "always"
    volumes:
      - /srv/riemann.config:/app/etc/riemann.config

- name: Wait for Riemann to come up
  wait_for: port="{{ riemann_port }}" delay=5 timeout=60
