---
- hosts: localhost
  remote_user: "{{ remote_user }}"
  pre_tasks:
    - include_vars: ../defaults/main.yml
  roles:
    - aws

- hosts: peer
  remote_user: "{{ remote_user }}"
  gather_facts: false
  become: yes
  become_method: sudo
  pre_tasks:
    # Ansible requires python2, which is not installed by default on Ubuntu Xenial
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - include_vars: ../defaults/main.yml
  vars:
    - prepare_onyx: no
  roles:
    - onyx_peers
